name: Release

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]


permissions:
  contents: write # Grant write access to repository contents
  actions: read # Grant read access to repository actions
  discussions: read # Grant read access to repository discussions

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest # Use ubuntu-latest to build, as it supports cross-compilation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Preparing Test Env
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}   
      - name: Setup Go
        uses: actions/setup-go@v5 # Action to set up the Go environment
        with:
          go-version: '^1.25' # Specify the Go version you want to use
      - run: go version

      - name: Build
        run: |
          # Set environment variables for cross-compilation
          # GOOS: target operating system
          # GOARCH: target architecture
          # CGO_ENABLED=0: Disable CGO for static linking (recommended for portability)
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o basicQuery-linux-amd64 ./cmd/basicQuery/basicQuery.go 
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o basicQuery-windows-amd64.exe ./cmd/basicQuery/basicQuery.go
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o basicQuery-darwin-amd64 ./cmd/basicQuery/basicQuery.go
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o basicQuery-linux-arm64 ./cmd/basicQuery/basicQuery.go
          GOOS=windows GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o basicQuery-windows-arm64.exe ./cmd/basicQuery/basicQuery.go
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o basicQuery-darwin-arm64 ./cmd/basicQuery/basicQuery.go
          
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o askToAllModels-linux-amd64 ./cmd/askToAllModels/askToAllModels.go 
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o askToAllModels-windows-amd64.exe ./cmd/askToAllModels/askToAllModels.go
          GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" -o askToAllModels-darwin-amd64 ./cmd/askToAllModels/askToAllModels.go
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o askToAllModels-linux-arm64 ./cmd/askToAllModels/askToAllModels.go
          GOOS=windows GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o askToAllModels-windows-arm64.exe ./cmd/askToAllModels/askToAllModels.go
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w" -o askToAllModels-darwin-arm64 ./cmd/askToAllModels/askToAllModels.go
          

      - name: Create Archives
        run: |
          tar -czvf basicQuery-linux-amd64.tar.gz basicQuery-linux-amd64
          tar -czvf basicQuery-darwin-amd64.tar.gz basicQuery-darwin-amd64
          zip basicQuery-windows-amd64.zip basicQuery-windows-amd64.exe
          tar -czvf basicQuery-linux-arm64.tar.gz basicQuery-linux-arm64
          tar -czvf basicQuery-darwin-arm64.tar.gz basicQuery-darwin-arm64
          zip basicQuery-windows-arm64.zip basicQuery-windows-arm64.exe
          tar -czvf askToAllModels-linux-amd64.tar.gz askToAllModels-linux-amd64
          tar -czvf askToAllModels-darwin-amd64.tar.gz askToAllModels-darwin-amd64
          zip askToAllModels-windows-amd64.zip askToAllModels-windows-amd64.exe
          tar -czvf askToAllModels-linux-arm64.tar.gz askToAllModels-linux-arm64
          tar -czvf askToAllModels-darwin-arm64.tar.gz askToAllModels-darwin-arm64
          zip askToAllModels-windows-arm64.zip askToAllModels-windows-arm64.exe

      - name: Calculate Sha256 hash
        run: |
          sha256sum basicQuery-* > SHA256.txt
          sha256sum askToAllModels-* >> SHA256.txt

      - name: Upload Release Asset for Linux/macOS
        uses: softprops/action-gh-release@v2.2.2
        with:
          body:  Release${{ env.RELEASE_VERSION }}
          files: |
            basicQuery-linux-amd64.tar.gz
            basicQuery-darwin-amd64.tar.gz
            basicQuery-windows-amd64.zip
            basicQuery-linux-arm64.tar.gz
            basicQuery-darwin-arm64.tar.gz
            basicQuery-windows-arm64.zip
            askToAllModels-linux-amd64.tar.gz
            askToAllModels-darwin-amd64.tar.gz
            askToAllModels-windows-amd64.zip
            askToAllModels-linux-arm64.tar.gz
            askToAllModels-darwin-arm64.tar.gz
            askToAllModels-windows-arm64.zip
            SHA256.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
